name = "Prajwal Saokar"
downloads-dir = "~/Downloads"

[gmail]
default = true
email = "prajwalsaokar@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "prajwalsaokar@gmail.com"
imap-passwd-cmd = "pass show Email/prajwalsaokar@gmail.com"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "prajwalsaokar@gmail.com"
smtp-passwd-cmd = "pass show Email/prajwalsaokar@gmail.com"
